
include: package:flutter_lints/rules.yaml

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - always_declare_return_types
    - avoid_print
    - prefer_final_fields
